### ISSUE TITLE
FieldMap.CopyStateFrom(FieldMap) is unecessarily internal

### ISSUE THREAD

**Issue by jpetterl** [connamara/quickfixn#224]
Hi,

We have many FIX end-points using different data dictionaries within the same process, serving different customers. We therefore intended to simply use the basic quick-fix assembly for functionality and tailor message types within different projects of our system.

The code-gen that generates the new messages based on the data dictionary creates a Clone() function as follows:
            public override Group Clone()
            {
                var clone = new NoStructuresGroup();
                clone.CopyStateFrom(this);
                return clone;
            }
... and the problem is that CopyStateFrom method is internal.

What is the thinking behind this method being internal? Is there any reason why it can't be protected or public? We intend to take the generated messages, change the namespace and host them in our assemblies, supplying the correct MessageFactory to the ThreadedSocketAcceptor to create them.

Thanks,
Petter

**Comment by jods4** [comment]
I am generating my own classes from a custom XML FIX definition.

I noticed the built-in group classes and the official generator implement `Clone`, using the internal `CopyStateFrom`. Since it's internal, that approach doesn't work when you use your own group classes.

Can I safely ignore `Clone` (i.e. not implement it)? 
If not, what's the best way to implement it, given I don't have access to `CopyStateFrom`?

**Comment by jods4** [comment]
@gbirchmeier This issue needs to be reopened.

If you generate your own typed messages in your assembly, you absolutely have to implement `Group.Clone()`, because `FieldMap.AddGroup` clones the group. If you don't you are left with generic `Group` instances -> there's just no reason to create strongly typed groups in the first place.

Now the problem is that the only efficient/reasonable way to clone a group is to call `FieldMap.CopyStateFrom`, which is what the Ruby code generator does, as well as all built-in types.

Since `CopyStateFrom` is internal, you can't call it from your own group classes and you're stuck.

**Comment by gbirchmeier** [comment]
@jods4, if you check the latest source, you'll see it's already public.  Looks like someone made this change some time ago as part of another feature.

**Comment by jods4** [comment]
@gbirchmeier Thanks! I'll check and upgrade my dependencies!

**Comment by gbirchmeier** [comment]
Are you using the nuget package?  We didn't create that, and it's way behind.  It's not officially supported.  (Recently the owner granted us ownership, so we may start publishing an official one, but that hasn't happened yet.)

So... yeah, don't use the nuget package.

**Comment by jods4** [comment]
Yes, I'm using the Nuget package `QuickFix.Net`, version 1.8.0.

It would be nice of you to publish an official package. Nuget is the only good way to manage dependencies. 🙏
