### ISSUE TITLE
disconnecting: Received msg type '5' when not logged on

### ISSUE THREAD

**Issue by lobster2012** [connamara/quickfixn#354]
Error while re-connect
disconnecting: Received msg type '5' when not logged on

**Comment by gbirchmeier** [comment]
This report is so insubstantial that I'm inclined to close it right now.

You got a log?  What version of QF/n are you using?

**Comment by lobster2012** [comment]
Sorry, now I can not give a logs file (later i will do it) . I  use last version.

**Comment by DanHarman** [comment]
Hi,

I've have this issue too, and it is due to immediately receiving a logout message in response to a login request from my side, when the sequence numbers are out.

It is a pretty misleading and unfortunately requires looking at the message log to diagnose, since it doesn't surface in the IApplication layer, which is not great in a support situation.

**Comment by cyphersys** [comment]
it's happening to me too. This issue is triggered when I sent a wrong pass on Login and the server throw a message 35=5 immediately before disconnecting.

Thank you

**Comment by gbirchmeier** [comment]
I believe the core of this is #856, which I've just run into myself (in a situation that is just like what @cyphersys describes).  I'm going to close this, as I think my writeup in that issue is pretty comprehensive and detailed.  (Let me know if you disagree.)

It's not going to be fun to fix...
