### ISSUE TITLE
Remove Ruby Code Generation

### ISSUE THREAD

**Issue by cbusbey** [connamara/quickfixn#400]
To make it easier to get started building and contributing to QuickFIXn, it would be good to rely more on the standard .net stack for message generation.  

A while ago we had a pr which was never merged that used T4 (https://github.com/connamara/quickfixn/pull/310).  We would like to revisit using T4 for code generation.  As an initial step, we will need a T4 implementation that 

1) is executed as part of the normal build script
2) is limited in scope to generate the generated code exactly as it is now. 

Once this gets in, this should free up some other issues and stale prs related to ruby code generation.

**Comment by gbirchmeier** [comment]
Working on a C# dotnet-standard (e.g. cross-platform) tool to analyze and generate code.
https://github.com/gbirchmeier/qfn-ddtool

It's not TT4, because that's too windows-specific.  Going forward, we should write to dotnet-standard (which means we can dev on *nix with VSCode, yay).

(Honestly, we don't really need a template engine.  Our templates are not complex.  A custom thing won't be reinventing the wheel too hard.)
