### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by jaredthirsk** [connamara/quickfixn#408]
.NET Core was recently released and it is an exciting new open source cross-platform development from Microsoft in the .NET landscape.  It would be great to have QuickFIX/n for .NET Core.

**Comment by damageboy** [comment]
I took a quick stab at this.

I have a ready to PR branch based on #218 that basically adds VS 2017 support (as in new .csproj format).

That branch simply moves into the new .csproj and adds nupkg files which are kind of mandatory if you want to live in the brave new world of .NET Core..

I made an early attempt at supporting .NET standard 1.3. I can definitely work.
There are going to be a lot of `#if NET_4_5_2` statements in the code but it will probably work pretty cleanly.

I will try to push this PR after #218 is accepted, but everything looks a bit too dormant now...

**Comment by damageboy** [comment]
@cbusbey anyway we can forward on this?
There's #218, My own "Move to new .csproj" branch which I can't even PR since It's based on #218, and the move to .NET Core (Perhaps .NET standard).

I already have my own branch compiling and passing all unit tests, and automatically generating .nupkgs, I would love to work on .NET core support, given that the bulk of the work has already been done by moving into the new csproj format, it's not just a matter of adding some targets and ifdefs...

But someone (hint hint :)) needs to start merging PRs to make this happen

**Comment by cbusbey** [comment]
@damageboy the referenced pr has merge conflicts

**Comment by damageboy** [comment]
The merge conflict is a single like of appveyor.yml to fix the nokogiri dependency...

The sort of benign thing that happens when PRs are unattended for months with no communication... :(

**Comment by damageboy** [comment]
Is there any update regarding this?
I would really love to move forward, I have a local branch with new csproj + netstandard 2.0 support all in place....

**Comment by cbusbey** [comment]
Any way you could help us out on this to push through?  The pr you referenced appears to be abandoned.  It would really help if someone branches #218, fixes the merge conflicts and prs those changes.  I can tell this is a big change you guys want in, we could just use a little help to grease the skids.

**Comment by akamyshanov** [comment]
@cbusbey this should be closed because of #469
