### ISSUE TITLE
DoNotSend exception not returned

### ISSUE THREAD

**Issue by mw911** [connamara/quickfixn#413]
From my point of view the DoNotSend exception should either not be catched by quickfixn or finally "forwarded" to the calling application. In Session.cs "SendRaw(Message message, int seqNum)" FALSE is returned. The problem is that if I send a message with sendToTarget no one can distinguish between message was not send due to raising this exception or due to other problems (e.g FIX session is not up). Depending on the result it might be neccessary to react differently.

In the "original" QuickFIX this is possible and should also be in quickfixn

                Try
                    If QuickFix.Session.sendToTarget(fixMessage, Me.fixSession) Then
                    Else
                    End If
                Catch ex As DoNotSend
                    NTService.Log.Info("A message was suppressed on purpose")
                End Try

**Comment by gbirchmeier** [comment]
I think perhaps you are misunderstanding the purpose of DoNotSend.

DoNotSend is intended for use by the application developer inside `ToApp()`.  If the application's logic has a situation in which a message should be aborted, it should throw a DoNotSend.  It's how the developer can say, "hey engine, don't send this message!"

DoNotSend will *never* be thrown unless the developer coded it.

So this logic is doing exactly what it's supposed to do.  The engine is intended to be the ultimate receiver of this exception; it should *not* be passed up the call stack.

I'm going to close this as not-a-bug.  Please reply if you need further explanation.

**Comment by mw911** [comment]
Many thanks for your instant answer today.

I think I don't misunderstand the purpose and I use it exactly like this. The problem is that the application (from the developer) might have different parts.
One part (in my case a thread which sends all files in a directory via FIX and deletes them afterwards if sending was successfull) and another part Two within ToApp() which might decide to not send the message based on further logic.
Now the question: How should the thread in part One know when it is fine to delete the file to prevent sending it another time if sendToTarget() returns False in case part Two throws a DoNotSend? As I've mentioned in my first comment the "original" QuickFIXEngine actually throws the exception also in sendToTarget() so the code I've provided works and I'm wondering why that behaviour should not be in QuickFIX/N.

I hope you agree that there are 3 different results when calling sendToTarget()
1) True
2) False
3) Exception DoNotSend

**Comment by gbirchmeier** [comment]
Ah, ok.  So the REAL problem is that you can't distinguish between a send-failure and a DoNotSend, because they both return false.  Now I can see where you're coming from.

I think, ultimately, you can design around this.

You already must have some kind of communication between Part One and Part Two (so that P2 can relay the return value to P1).  Therefore, you simply need to allow `ToApp()` access to that communication channel, so that it can inform P1 when a DoNotSend is about to be thrown.

I think that such a solution will not be disruptive to your existing design.

**Comment by mw911** [comment]
Many thanks again for your answer and I really appreciate. (I never thought I would get feedback at all but now I know better).

It could be possible to design around this but actually ToApp() contains the business logic while my sender thread has no logic at all and both don't have anything in common. I am also not worried about performance but I have even more than one dummy sender process so I can't be sure if ToApp() actually processes the message thread A just tries to send.

If you don't see it as a bug or enhancement I just change the single line of code myself - no problem at all. Before my request I already changed it to always return true at least and now I've changed it to "throw new DoNotSend();" and everything is working fine.

Just for information: I am currently "converting" my application from QuickFIX with the .Net wrapper to QuickFIX/N and this is the only problem left and I found it worth raising it in case other developers will face the same but it is up to you to see it as a bug.

**Comment by gbirchmeier** [comment]
> actually ToApp() contains the business logic

That's an unorthodox thing to do, I think.

> I am currently "converting" my application from QuickFIX with the .Net wrapper to QuickFIX/N and this is the only problem left and I found

I just looked at the QuickFIX source and it has the same behavior as QF/n.  It catches DoNotSend and returns false.

**Comment by mw911** [comment]
Just checked too and you are right. It looks like my ex-colleague changed that part in the code in version 1.13.3 to make it work as it is right now. So I'm really sorry for my bug in the first place. Still I think the exception should be passed up the call stack. Strange that I should be the only one with that problem because very often I see people deal with similar applications (send fix messages from files via FIX).

Just one last question: Why do say say it would be an unorthodox thing to do? FromApp() and ToApp() are the only places to handle FIX messages. I mean from there I call MessageCracker but of course the logic is not actually inside toapp.

**Comment by gbirchmeier** [comment]
A few reasons:

1) You should not do a lot of work inside the callbacks, because QF does not start working on the next incoming message until the callback returns.  If you have expensive work to do, you should defer it to another thread.  (This is more about FromApp and OnMessage, rather than ToApp).

2) Instead of calling DoNotSend inside ToApp, is it possible that you could detect this condition earlier and simply avoid calling `sendToTarget` or whatever?  I don't see why it can't be detected before it gets to ToApp.

Interception via ToApp is really more appropriate for light-logic tasks.  I can't think of a good example because I've literally never used this callback.  (Though I have used ToAdmin to add usernames/passwords to outgoing Login messages, which is pretty common.)
