### ISSUE TITLE
Creating  components

### ISSUE THREAD

**Issue by QFikus** [connamara/quickfixn#477]
Hi,

I need help with creating components, correctly groups without delimiters.
Or how i can manage order of fields whom are not in groups?

It isnt issue, but i dont know where to find answer any more.

Thank you.

**Comment by gbirchmeier** [comment]
You should ask your question on the mailing list or on StackOverflow.  (If using the mailing list, please send to the correct list address.  You previously sent your question to the list-owner address; I don't know how you got that address, but we ignore anything that goes to wrong addresses.)

The mail list information is here: http://quickfixn.org/help/

There's a good answer here about how QF components work:  
https://stackoverflow.com/questions/29772481/difference-between-group-and-component-in-quickfix-j

You cannot manage order of fields that are not in groups, because according to FIX specifications this order is not important.

I'm closing this issue because it's not an issue.
