### ISSUE TITLE
Ignore repeating group without a DataDictionary

### ISSUE THREAD

**Issue by alinmotogna** [connamara/quickfixn#480]
I spent about 2 hours trying to figure out a workaround for my issue, before eventually decided to ask a question here.

My session - which is not using DataDictionary - is receiving a repeating group that I am trying to ignore with:
> ValidateLengthAndChecksum=N

based on this doc snippet:
> You can also use this to force acceptance of repeating groups without a data dictionary

However this message

`20180410-02:08:42.447 : 8=FIX.4.2^A9=264^A35=6^A122=20180410-01:32:44.278^A56=..^A116=..^A115=..^A52=20180410-02:08:42.330^A49=..^A43=..^A34=..^A62=20180410-11:09:41.000^A28=..^A27=..^A55=..^A54=..^A25=..^A199=2^A104=M^A104=I^A23=..^A76=..^A215=..^A216=..^A217=..^A207=..^A130=..^A10=043^A`

still gets rejected because of 199 group and two 104 tags:

`20180410-02:08:42.463 : 8=FIX.4.2^A9=137^A35=3^A34=29784^A49=..^A52=20180410-02:08:42.463^A56=..^A128=..^A129=..^A45=..^A58=Tag appears more than once^A371=104^A372=6^A10=035^A`

Anything I could do to accept messages with repeating tags without using a DataDictionary?

**Comment by gbirchmeier** [comment]
"You can also use this to force acceptance of repeating groups without a data dictionary."

That sounds super wrong.  Will investigate, but pretty sure that needs to be struck from the docs.

**Comment by gbirchmeier** [comment]
*Now* I understand why the docs say

> You can also use this to force acceptance of repeating groups without a data dictionary

It's because, when there's no DD, in some cases messages with groups will be parsed incorrectly and some fields will get dropped, causing the checksum and length to not match.  I forget the specifics of why this can work, but it's certainly not something to count on.

So basically this message is still tremendously stupid.  It's advising users to make one bad decision to correct another bad decision.  I'm taking it out.

If you have repeating groups, you should ALWAYS use a DataDictionary.  Full stop.
