### ISSUE TITLE
Specifying orders of field.

### ISSUE THREAD

**Issue by bhavishyagoyal12** [connamara/quickfixn#491]
Quickfixn sort fields  according to Number but my acceptor required fields in following order . Can you please let me know is it possible to achieve this ?

8=FIX.4.3|9=235|35=R|34=1424|49=quote.TestOrg.TestUser.dev|52=20140226-
14:47:59.947|56=client.fxgrid.integral.com|128=BrkX|131=RFSOT1|146=1|55=USD/JP
Y|167=FOR|54=1|38=1000000|64=2W|40=D|126=20140226-14:02:00.946|60=20140226-
14:47:59.946|15=USD|10=076|

**Comment by gbirchmeier** [comment]
In FIX, outside of repeating groups, the order of fields does not matter.  I'm sure you are partially mistaken in what your actual problem is.

I suspect what's really happening is that your config is not configured with a correct DataDictionary, and because of that, your 146 repeating group's fields are not being ordered correctly.

Does your config contain the following?:

```
UseDataDictionary=Y
DataDictionary=path/to/your/dd.xml
```

Your file should be based on FIX43.xml which is found in `spec\fix\` in the downloadable.  You will probably need to [make some changes](http://quickfixn.org/tutorial/custom-fields-groups-and-messages.html) according to your counterparty's specs.

**Comment by mquwaider** [comment]
I have the same issue I need to sort the fields tags in the Fix message 4.2, the admin server want the tag 47 before the tag 1 when sending message tag D.

**Comment by gbirchmeier** [comment]
@mquwaider - your admin server is asking something that is not FIX standard.  As I already said, in FIX, the order of fields (outside of repeating groups) does not and should not matter.  Requiring 47 before 1 is simply not standard FIX.  You'd have to hack the engine to make this happen.

I'm closing this issue.  Please ask further followups on the mailing list, not here.

**Comment by mquwaider** [comment]
Thank you, but can you tell me which part of the QuickFix engine is responsible for sorting Fix message.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
