### ISSUE TITLE
Disabling sessions [via web interface]

### ISSUE THREAD

**Issue by mrefky** [connamara/quickfixn#516]
Disabling session using the web interface does not work as expected:
1. The gateway sends logout in response to logon message but this does not disconnect the session and all sent messages are sent to the application.
2. when the application is restarted the session becomes enabled.
3. The web interface still shows the session as disabled but the user as logged in.

**Comment by gbirchmeier** [comment]
I'm honestly not sure if the web interface is something we should keep distributing.  It's cute for a demo or maybe monitoring in certain situations, but I wouldn't recommend it for any kind of production use.

Regarding item 2:  Oh certainly.  The web interface only changes session settings _in memory_; it doesn't save them anywhere.  On restart, everything is reloaded from config files or the app's code.

I may take another look after I get the next release out.  (However, I may choose to delete the the disable-session feature from the page rather than attempt to fix it.)
