### ISSUE TITLE
Release 1.9 is missing on nuget

### ISSUE THREAD

**Issue by aukolov** [connamara/quickfixn#564]
Please advise when do you plan to publish version 1.9 on nuget. 
If it is not in immediate plans, is version 1.9 stable to build by myself and use in production?

Thanks

**Comment by VinceAvery** [comment]
I also need this.

**Comment by gbirchmeier** [comment]
I literally just answered the question [yesterday](https://github.com/connamara/quickfixn/issues/563).

But here it is again:

This is in our plans as soon as we have some time for it.

But please note: any current NuGet packages that are out there were not created by us and are completely unauthorized. We have never published a NuGet package.

Also, using a Nuget package means you're not using a build tailored for your specific interface, with typesafe message and field functions. I generally recommend that all seasoned users users should regenerate the QF/n source off of their own DD and make a custom build.

I guess I'll leave this issue open so people will find it and see it.

**Comment by gbirchmeier** [comment]
And yes, 1.9 is considered stable for production.

**Comment by aukolov** [comment]
@gbirchmeier , shame, I overlooked your previous response. Thanks, closing.

**Comment by gbirchmeier** [comment]
I'm going to leave it open so future askers can find it.

**Comment by harleybl** [comment]
The top 2 Nuget Packages for 1.8 have over 76k downloads. It is a bit confusing since the most popular one lists Connamara Systems LLC as an author. Wouldn't it be better to push out an official Nuget Package rather than letting users be misled? 

I get your point about it facilitating non-best practices with respect to type safety of message types for the data dictionary, but realistically how many people actually do that? The [documentation](http://quickfixn.org/tutorial/custom-fields-groups-and-messages.html) doesn't rebuilding from source with your own DD if you have custom types or messages. It basically says that if you have a custom field you have to fall back to using Get/Set field API. 

In my own projects, I often have to fall back to using the Get/Set field methods because I want to treat ExecutionReport or TradeCaptureReports the same regardless of whether they came from FIX4.2 or FIX4.4, but that is a separate issue from having or not having an official NuGet package.

I feel that the benefits of having an official NuGet package outweigh the costs.

**Comment by gbirchmeier** [comment]
I already said that we fully plan to make an official Nuget package.  But the thing is, QF/n doesn't pay the bills (only PR benefits).  I'm knee-deep in a client project right now.  This is gonna have to wait until me or one of my colleagues is between projects.  (Or if someone wants to pay us to prioritize it.)

**Comment by harleybl** [comment]
Sorry I misread that first line based on the rest of it.

**Comment by fourpastmidnight** [comment]
It only took an hour or two to tweak the projects and release script to enable creating NuGet packages. Now all that's needed is an official NuGet account so you guys can obtain an API key and push your very own packages to Nuget.org. [Here are the docs for publishing packages to NuGet.](https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package) You can also [reserve your own package ID prefix.](https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation) This can help people identify that these are official packages.

HTH.
