### ISSUE TITLE
Sequence number reset at sunday midnight

### ISSUE THREAD

**Issue by ajitag09** [connamara/quickfixn#666]
I have configured sun-sun weekly session with start and end time as 00:00:00, my sequence number is getting reset at sunday midnight. Is there any way such that sequence number doesn't get reset when I start the fix engine on Monday. I want 24/7 system.

**Comment by mgatny** [comment]
The session must end at some point so that MsgSeqNums can be reset, instead of growing forever (which also means the message store, for honoring ResendRequests can be cleared).  The protocol recommends 24 hour sessions.  Week-long sessions are supported because some counterparties (e.g. CME) use them.  If you would like to discuss further, please ask on the qf/n mailing list: http://lists.quickfixn.com/listinfo.cgi/quickfixn-quickfixn.com

**Comment by ajitag09** [comment]
If I want to reset the sequence number on Wednesday , but continue the rollover state of Friday on Monday . What needs to be done for that
