### ISSUE TITLE
Unhelpful behaviour for unknown fields

### ISSUE THREAD

**Issue by JulianBirch** [connamara/quickfixn#789]
The simplest way to demonstrate this is to take a fix message, parse it with no data dictionary at all and then convert it back to a string. Under those circumstances, it's entirely possible that QuickFIX will reorder some of the tags, which is undesirable but understandable. However, it retains tags 9 and 10, which are incorrect when you attempt to reserialize using ToString().

It's easy enough to work around: you just remove 9 and 10 after parsing.

**Comment by gbirchmeier** [comment]
Why would you parse a message without a DD?

The 9/10 issue you cite isn't even the bad part.  The bad part is that _it's impossible to parse repeating groups without a DD!_   The DD-less parser can't know when a group begins or ends, and can't distinguish a group from a repeated-tag error.  (And in practice, all counterparties use repeating groups-- non-DD situations aren't actually real-life situations.)

I don't really understand your use case.  But I know that the engine can serialize messages just fine for its own purposes.

I'm going to close this because I don't see the merit, but feel free to reply if you think there is more here that I'm not seeing.
